# Generated by Django 2.2.6 on 2020-02-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipe',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
